//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.Emcos.DataForCalculateNormativ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.Emcos.DataForCalculateNormativ.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация не удалась,
        ///неверные имя пользователя или пароль..
        /// </summary>
        public static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция отменена..
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершено..
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну или несколько групп..
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        ///Описание ошибки:
        ///{0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл конфигурации программы &apos;{0}&apos;.
        ///Будет произведено получение данных с сервиса Emcos Corporate.
        ///Операция займет некоторое время, пожалуйста, подождите..
        /// </summary>
        public static string ErrorNotFoundPointsList {
            get {
                return ResourceManager.GetString("ErrorNotFoundPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при загрузке конфигурации программы.
        ///Описание ошибки:
        ///{0}.
        /// </summary>
        public static string ErrorOnLoadPointsList {
            get {
                return ResourceManager.GetString("ErrorOnLoadPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при сохранении конфигурации программы.
        ///Описание ошибки:
        ///{0}.
        /// </summary>
        public static string ErrorOnSavePointsList {
            get {
                return ResourceManager.GetString("ErrorOnSavePointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить
        ///данные.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных с сервиса Emcos Corporate..
        /// </summary>
        public static string GettingDataStatus {
            get {
                return ResourceManager.GetString("GettingDataStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет ответа от сервиса, проверьте имя сервиса..
        /// </summary>
        public static string IncorrectService {
            get {
                return ResourceManager.GetString("IncorrectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать
        ///получение данных.
        /// </summary>
        public static string InterruptGet {
            get {
                return ResourceManager.GetString("InterruptGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать
        ///обновление списка.
        /// </summary>
        public static string InterruptUpdate {
            get {
                return ResourceManager.GetString("InterruptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступа, проверьте имя пользователя и пароль..
        /// </summary>
        public static string NotHavePermission {
            get {
                return ResourceManager.GetString("NotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет произведено получение данных с сервиса Emcos Corporate.
        ///Операция займет продолжительное время,
        ///пожалуйста, подождите..
        /// </summary>
        public static string OnGettingData {
            get {
                return ResourceManager.GetString("OnGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет произведено получение данных с сервиса Emcos Corporate.
        ///Операция займет некоторое время,
        ///пожалуйста, подождите..
        /// </summary>
        public static string OnUpdatingPointsList {
            get {
                return ResourceManager.GetString("OnUpdatingPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан отчёт в настройках программы..
        /// </summary>
        public static string ReportNotSpecified {
            get {
                return ResourceManager.GetString("ReportNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить
        ///результат.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение результатов.
        /// </summary>
        public static string SavingInProgress {
            get {
                return ResourceManager.GetString("SavingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер {0} доступен.
        /// </summary>
        public static string ServerAvailability {
            get {
                return ResourceManager.GetString("ServerAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис {0} доступен.
        /// </summary>
        public static string ServiceAvailability {
            get {
                return ResourceManager.GetString("ServiceAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки
        ///программы.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение работы.
        /// </summary>
        public static string TerminatingMessage {
            get {
                return ResourceManager.GetString("TerminatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить
        ///список.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление списка точек.
        /// </summary>
        public static string UpdatingInProgress {
            get {
                return ResourceManager.GetString("UpdatingInProgress", resourceCulture);
            }
        }
    }
}
