//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.Emcos.DataForCalculateNormativ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.Emcos.DataForCalculateNormativ.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.\nОписание ошибки:\n{0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл конфигурации программы &apos;{0}&apos;.\nБудет произведено получение данных с сервиса Emcos Corporate.\nОперация займет некоторое время, пожалуйста, подождите..
        /// </summary>
        public static string ErrorNotFoundPointsList {
            get {
                return ResourceManager.GetString("ErrorNotFoundPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при загрузке конфигурации программы.\nОписание ошибки:\n{0}.
        /// </summary>
        public static string ErrorOnLoadPointsList {
            get {
                return ResourceManager.GetString("ErrorOnLoadPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при сохранении конфигурации программы.\nОписание ошибки:\n{0}.
        /// </summary>
        public static string ErrorOnSavePointsList {
            get {
                return ResourceManager.GetString("ErrorOnSavePointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить
        ///данные.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать
        ///получение данных.
        /// </summary>
        public static string InterruptGet {
            get {
                return ResourceManager.GetString("InterruptGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать
        ///обновление списка.
        /// </summary>
        public static string InterruptUpdate {
            get {
                return ResourceManager.GetString("InterruptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет произведено получение данных с сервиса Emcos Corporate.\nОперация займет продолжительное время, пожалуйста, подождите..
        /// </summary>
        public static string OnGettingData {
            get {
                return ResourceManager.GetString("OnGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет произведено получение данных с сервиса Emcos Corporate.\nОперация займет некоторое время, пожалуйста, подождите..
        /// </summary>
        public static string OnUpdatingPointsList {
            get {
                return ResourceManager.GetString("OnUpdatingPointsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить
        ///результат.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение работы.
        /// </summary>
        public static string TerminatingMessage {
            get {
                return ResourceManager.GetString("TerminatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить
        ///список.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
