//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.WORK.AramisChetchiki.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double FontSize {
            get {
                return ((double)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e:\\aramis\\DiskF\\OSHM\\aramis")]
        public string AramisPath {
            get {
                return ((string)(this["AramisPath"]));
            }
            set {
                this["AramisPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataStorePath {
            get {
                return ((string)(this["DataStorePath"]));
            }
            set {
                this["DataStorePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TMP.WORK.AramisChetchiki.ViewModel.Theme Theme {
            get {
                return ((global::TMP.WORK.AramisChetchiki.ViewModel.Theme)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ObjectModel.ObservableCollection<Xceed.Wpf.DataGrid.TableField> ChangesOfMetersFields {
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<Xceed.Wpf.DataGrid.TableField>)(this["ChangesOfMetersFields"]));
            }
            set {
                this["ChangesOfMetersFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ViewAsList")]
        public global::TMP.WORK.AramisChetchiki.Model.InfoViewType SelectedSummaryView {
            get {
                return ((global::TMP.WORK.AramisChetchiki.Model.InfoViewType)(this["SelectedSummaryView"]));
            }
            set {
                this["SelectedSummaryView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ObjectModel.ObservableCollection<TMP.WORK.AramisChetchiki.Model.Departament> Departaments {
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<TMP.WORK.AramisChetchiki.Model.Departament>)(this["Departaments"]));
            }
            set {
                this["Departaments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ObjectModel.ObservableCollection<Xceed.Wpf.DataGrid.TableField> SummaryInfoFields {
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<Xceed.Wpf.DataGrid.TableField>)(this["SummaryInfoFields"]));
            }
            set {
                this["SummaryInfoFields"] = value;
            }
        }
    }
}
