//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.Emcos.DataForCalculateNormativ.EmcosTestWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ksmlab.ru/", ConfigurationName="EmcosTestWebService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetPointInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPointInfo(string UserName, string PPOINT_CODE_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetPointInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPointInfoAsync(string UserName, string PPOINT_CODE_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetGRInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetGRInfo(string UserName, string PGR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetGRInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetGRInfoAsync(string UserName, string PGR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetMLInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMLInfo(string UserName, string PML_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetMLInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetMLInfoAsync(string UserName, string PML_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSTPLData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSTPLData(string UserName, string PPOINT_CODE_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSTPLData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSTPLDataAsync(string UserName, string PPOINT_CODE_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetRPARGRCacheData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRPARGRCacheData(string UserName, string PGR_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetRPARGRCacheData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRPARGRCacheDataAsync(string UserName, string PGR_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDayEnergyFromGroup_3min", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDayEnergyFromGroup_3min(string UserName, string PGR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDayEnergyFromGroup_3min", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDayEnergyFromGroup_3minAsync(string UserName, string PGR_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetGroupValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetGroupValue(string UserName, string PGR_ID, string PML_ID, string Interval, string Offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetGroupValue", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetGroupValueAsync(string UserName, string PGR_ID, string PML_ID, string Interval, string Offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetRPARGRData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRPARGRData(string UserName, string PGR_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetRPARGRData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRPARGRDataAsync(string UserName, string PGR_ID, string PML_ID, string PBT, string PET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetLPTYInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLPTYInfo(string UserName, string LPTY_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetLPTYInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLPTYInfoAsync(string UserName, string LPTY_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEParams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSEParams(string UserName, string SE_ID, string LPTY_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEParams", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSEParamsAsync(string UserName, string SE_ID, string LPTY_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDPInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDPInfo(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDPInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDPInfoAsync(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/Get_POINT_SRC_DP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_POINT_SRC_DP(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/Get_POINT_SRC_DP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_POINT_SRC_DPAsync(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEElements", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSEElements(string UserName, string SRC_ID, string POINT_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEElements", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSEElementsAsync(string UserName, string SRC_ID, string POINT_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEElementsSEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSEElementsSEP(string UserName, string SRC_ID, string POINT_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetSEElementsSEP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSEElementsSEPAsync(string UserName, string SRC_ID, string POINT_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEParams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SetSEParams(string UserName, string SE_ID, string LPTY_ID, string LPTY_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEParams", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SetSEParamsAsync(string UserName, string SE_ID, string LPTY_ID, string LPTY_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetDPEnabledParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SetDPEnabledParam(string UserName, string DP_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetDPEnabledParam", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SetDPEnabledParamAsync(string UserName, string DP_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDPChannelsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDPChannelsInfo(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/GetDPChannelsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDPChannelsInfoAsync(string UserName, string DP_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetPHEnabledParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SetPHEnabledParam(string UserName, string PH_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetPHEnabledParam", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SetPHEnabledParamAsync(string UserName, string PH_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEEnabledParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SetSEEnabledParam(string UserName, string SE_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEEnabledParam", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SetSEEnabledParamAsync(string UserName, string SE_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEPEnabledParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SetSEPEnabledParam(string UserName, string SEP_ID, string ENABLED_VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ksmlab.ru/SetSEPEnabledParam", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SetSEPEnabledParamAsync(string UserName, string SEP_ID, string ENABLED_VALUE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : TMP.Work.Emcos.DataForCalculateNormativ.EmcosTestWebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<TMP.Work.Emcos.DataForCalculateNormativ.EmcosTestWebService.ServiceSoap>, TMP.Work.Emcos.DataForCalculateNormativ.EmcosTestWebService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetPointInfo(string UserName, string PPOINT_CODE_ID) {
            return base.Channel.GetPointInfo(UserName, PPOINT_CODE_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPointInfoAsync(string UserName, string PPOINT_CODE_ID) {
            return base.Channel.GetPointInfoAsync(UserName, PPOINT_CODE_ID);
        }
        
        public System.Data.DataTable GetGRInfo(string UserName, string PGR_ID) {
            return base.Channel.GetGRInfo(UserName, PGR_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetGRInfoAsync(string UserName, string PGR_ID) {
            return base.Channel.GetGRInfoAsync(UserName, PGR_ID);
        }
        
        public System.Data.DataTable GetMLInfo(string UserName, string PML_ID) {
            return base.Channel.GetMLInfo(UserName, PML_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetMLInfoAsync(string UserName, string PML_ID) {
            return base.Channel.GetMLInfoAsync(UserName, PML_ID);
        }
        
        public System.Data.DataTable GetSTPLData(string UserName, string PPOINT_CODE_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetSTPLData(UserName, PPOINT_CODE_ID, PML_ID, PBT, PET);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSTPLDataAsync(string UserName, string PPOINT_CODE_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetSTPLDataAsync(UserName, PPOINT_CODE_ID, PML_ID, PBT, PET);
        }
        
        public System.Data.DataTable GetRPARGRCacheData(string UserName, string PGR_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetRPARGRCacheData(UserName, PGR_ID, PML_ID, PBT, PET);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRPARGRCacheDataAsync(string UserName, string PGR_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetRPARGRCacheDataAsync(UserName, PGR_ID, PML_ID, PBT, PET);
        }
        
        public System.Data.DataTable GetDayEnergyFromGroup_3min(string UserName, string PGR_ID) {
            return base.Channel.GetDayEnergyFromGroup_3min(UserName, PGR_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDayEnergyFromGroup_3minAsync(string UserName, string PGR_ID) {
            return base.Channel.GetDayEnergyFromGroup_3minAsync(UserName, PGR_ID);
        }
        
        public System.Data.DataTable GetGroupValue(string UserName, string PGR_ID, string PML_ID, string Interval, string Offset) {
            return base.Channel.GetGroupValue(UserName, PGR_ID, PML_ID, Interval, Offset);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetGroupValueAsync(string UserName, string PGR_ID, string PML_ID, string Interval, string Offset) {
            return base.Channel.GetGroupValueAsync(UserName, PGR_ID, PML_ID, Interval, Offset);
        }
        
        public System.Data.DataTable GetRPARGRData(string UserName, string PGR_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetRPARGRData(UserName, PGR_ID, PML_ID, PBT, PET);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRPARGRDataAsync(string UserName, string PGR_ID, string PML_ID, string PBT, string PET) {
            return base.Channel.GetRPARGRDataAsync(UserName, PGR_ID, PML_ID, PBT, PET);
        }
        
        public System.Data.DataTable GetLPTYInfo(string UserName, string LPTY_ID) {
            return base.Channel.GetLPTYInfo(UserName, LPTY_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLPTYInfoAsync(string UserName, string LPTY_ID) {
            return base.Channel.GetLPTYInfoAsync(UserName, LPTY_ID);
        }
        
        public System.Data.DataTable GetSEParams(string UserName, string SE_ID, string LPTY_ID) {
            return base.Channel.GetSEParams(UserName, SE_ID, LPTY_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSEParamsAsync(string UserName, string SE_ID, string LPTY_ID) {
            return base.Channel.GetSEParamsAsync(UserName, SE_ID, LPTY_ID);
        }
        
        public System.Data.DataTable GetDPInfo(string UserName, string DP_ID) {
            return base.Channel.GetDPInfo(UserName, DP_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDPInfoAsync(string UserName, string DP_ID) {
            return base.Channel.GetDPInfoAsync(UserName, DP_ID);
        }
        
        public System.Data.DataTable Get_POINT_SRC_DP(string UserName, string DP_ID) {
            return base.Channel.Get_POINT_SRC_DP(UserName, DP_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_POINT_SRC_DPAsync(string UserName, string DP_ID) {
            return base.Channel.Get_POINT_SRC_DPAsync(UserName, DP_ID);
        }
        
        public System.Data.DataTable GetSEElements(string UserName, string SRC_ID, string POINT_ID) {
            return base.Channel.GetSEElements(UserName, SRC_ID, POINT_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSEElementsAsync(string UserName, string SRC_ID, string POINT_ID) {
            return base.Channel.GetSEElementsAsync(UserName, SRC_ID, POINT_ID);
        }
        
        public System.Data.DataTable GetSEElementsSEP(string UserName, string SRC_ID, string POINT_ID) {
            return base.Channel.GetSEElementsSEP(UserName, SRC_ID, POINT_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSEElementsSEPAsync(string UserName, string SRC_ID, string POINT_ID) {
            return base.Channel.GetSEElementsSEPAsync(UserName, SRC_ID, POINT_ID);
        }
        
        public System.Data.DataTable SetSEParams(string UserName, string SE_ID, string LPTY_ID, string LPTY_VALUE) {
            return base.Channel.SetSEParams(UserName, SE_ID, LPTY_ID, LPTY_VALUE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SetSEParamsAsync(string UserName, string SE_ID, string LPTY_ID, string LPTY_VALUE) {
            return base.Channel.SetSEParamsAsync(UserName, SE_ID, LPTY_ID, LPTY_VALUE);
        }
        
        public System.Data.DataTable SetDPEnabledParam(string UserName, string DP_ID, string ENABLED_VALUE) {
            return base.Channel.SetDPEnabledParam(UserName, DP_ID, ENABLED_VALUE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SetDPEnabledParamAsync(string UserName, string DP_ID, string ENABLED_VALUE) {
            return base.Channel.SetDPEnabledParamAsync(UserName, DP_ID, ENABLED_VALUE);
        }
        
        public System.Data.DataTable GetDPChannelsInfo(string UserName, string DP_ID) {
            return base.Channel.GetDPChannelsInfo(UserName, DP_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDPChannelsInfoAsync(string UserName, string DP_ID) {
            return base.Channel.GetDPChannelsInfoAsync(UserName, DP_ID);
        }
        
        public System.Data.DataTable SetPHEnabledParam(string UserName, string PH_ID, string ENABLED_VALUE) {
            return base.Channel.SetPHEnabledParam(UserName, PH_ID, ENABLED_VALUE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SetPHEnabledParamAsync(string UserName, string PH_ID, string ENABLED_VALUE) {
            return base.Channel.SetPHEnabledParamAsync(UserName, PH_ID, ENABLED_VALUE);
        }
        
        public System.Data.DataTable SetSEEnabledParam(string UserName, string SE_ID, string ENABLED_VALUE) {
            return base.Channel.SetSEEnabledParam(UserName, SE_ID, ENABLED_VALUE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SetSEEnabledParamAsync(string UserName, string SE_ID, string ENABLED_VALUE) {
            return base.Channel.SetSEEnabledParamAsync(UserName, SE_ID, ENABLED_VALUE);
        }
        
        public System.Data.DataTable SetSEPEnabledParam(string UserName, string SEP_ID, string ENABLED_VALUE) {
            return base.Channel.SetSEPEnabledParam(UserName, SEP_ID, ENABLED_VALUE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SetSEPEnabledParamAsync(string UserName, string SEP_ID, string ENABLED_VALUE) {
            return base.Channel.SetSEPEnabledParamAsync(UserName, SEP_ID, ENABLED_VALUE);
        }
    }
}
